# Generated by Django 4.2.27 on 2026-02-02 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(choices=[('restaurant', 'Restaurant/Food'), ('retail', 'Retail/Shop'), ('transport', 'Transport/Logistics'), ('real_estate', 'Real Estate'), ('consulting', 'Consulting/Services'), ('agriculture', 'Agriculture'), ('manufacturing', 'Manufacturing'), ('technology', 'Technology'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('hospitality', 'Hospitality'), ('fashion', 'Fashion/Beauty'), ('construction', 'Construction'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=50)),
                ('business_type', models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('limited_liability', 'Limited Liability Company'), ('plc', 'Public Limited Company'), ('cooperative', 'Cooperative'), ('other', 'Other')], max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('color', models.CharField(default='#6B21A8', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_currency', models.CharField(default='NGN', max_length=3)),
                ('fiscal_year_start', models.DateField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_businesses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_businesses', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(max_length=20)),
                ('account_type', models.CharField(blank=True, choices=[('current', 'Current Account'), ('savings', 'Savings Account'), ('domiciliary', 'Domiciliary Account')], max_length=20, null=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('provider', models.CharField(choices=[('mono', 'Mono'), ('okra', 'Okra'), ('manual', 'Manual')], default='manual', max_length=50)),
                ('provider_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_institution_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_access_token', models.TextField(blank=True, null=True)),
                ('provider_refresh_token', models.TextField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed'), ('disconnected', 'Disconnected')], default='active', max_length=50)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('balance_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('sync_frequency_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='businesses.business')),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('disconnected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disconnected_bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organizations.organization')),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['organization'], name='businesses_organiz_ca4027_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['organization', 'is_active'], name='businesses_organiz_07f53f_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['industry'], name='businesses_industr_b4265c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['business'], name='bank_accoun_busines_b1826a_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['organization'], name='bank_accoun_organiz_a54d96_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['sync_status', 'next_sync_at'], name='bank_accoun_sync_st_ffcbf2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('provider', 'provider_account_id')},
        ),
    ]
